### PR TITLE
feat: Add PlatformIO support

### PR DESCRIPTION
**Pull request by skorokithakis**
This now sets the correct hardware UIDs etc.

### CODE REVIEW

**Comment by AndunHH** [comment]
Great! This works. I tested it in vscode with plattformio and it is also compatible with the arduino IDE!

I just scrammbled with the merge here, due to my updated comment commit a few minutes ago. ;) 
I'll fix it and merge this request.

**Comment by AndunHH** [comment]
One step forward, two back --- ok, one to the side and then two forward ... ;)

The arduino IDE is very picky with the name of the folder where the .ino file is located. I didn't succeed to commit my commits to this pull request, therefore I created a branch based on you pull request:

https://github.com/AndunHH/spacemouse/tree/skorokithakis-feat-platformio 

I tried to fix it using the src_dir parameter in plattformio.ini.

What do you think about it?

**Comment by skorokithakis** [comment]
Oh, that looks good to me!

**Comment by AndunHH** [comment]
done in c9ebd67

**Comment by skorokithakis** [comment]
Thanks!

**Pull request merged**
