### PR TITLE
Update config_sample.h

### PR DESCRIPTION
**Pull request by evolventum**
done with full button list of byteIDs for SpaceMouse Pro Wireless model

### CODE REVIEW

**Comment by AndunHH** [comment]
Did you change HIDMAX BUTTONS in https://github.com/AndunHH/spacemouse/blob/main/spacemouse-keys%2FhidInterface.h#L5  to 32? 
Because you found a value bigger than 24…

**Comment by AndunHH** [comment]
I checked it in the 3Dconnexion trainer and it is working with my small update. 

Thanks for finding out all those bits!

**Comment by evolventum** [comment]
> I checked it in the 3Dconnexion trainer and it is working with my small update.
> 
> Thanks for finding out all those bits!

I just take information from this place https://github.com/openantz/antz/wiki/3D-Mouse#developers
There are standard button list for many modern 3dx devices and bit mask for our SMPro model

Bit I didn't understand why 3dx driver receives two HID packet bytes with eventID 1 and 2 (older Logitech scheme) but didn't see any movements when controller transfer one big packet XYZrXrYrZ (Translate & Rotate) with eventID = 1

**Comment by AndunHH** [comment]
> Bit I didn't understand why 3dx driver receives two HID packet bytes with eventID 1 and 2 (older Logitech scheme) but didn't see any movements when controller transfer one big packet XYZrXrYrZ (Translate & Rotate) with eventID = 1

Have you tried and changed the coding also in the hid descriptor to one big report#1 instead of the actual report id#1 and id#2 with only translation and only rotation?

As it is working now, I see no cause to change the working behavior. Do you?

**Comment by evolventum** [comment]
> > Bit I didn't understand why 3dx driver receives two HID packet bytes with eventID 1 and 2 (older Logitech scheme) but didn't see any movements when controller transfer one big packet XYZrXrYrZ (Translate & Rotate) with eventID = 1
> 
> Have you tried and changed the coding also in the hid descriptor to one big report#1 instead of the actual report id#1 and id#2 with only translation and only rotation?
> 
> As it is working now, I see no cause to change the working behavior. Do you?

yepp. tried changing code in hidInterface.h and in old version hidInterface.cpp where it was possible (without cases) - driver didnt see any motion. but its OK, logitech-style works perfect!

**Comment by AndunHH** [comment]
Ok! Very intersting, thanks for the test.

Then we stay as it is.

**Pull request merged**
